syntax = "proto3";

option csharp_namespace = "Discount.Application.Protos";

service DiscountProtoService {
	rpc GetDiscountByProductId(GetDiscountByProductIdRequest) returns (CouponModel);
	rpc GetDiscountByProductName(GetDiscountByProductNameRequest) returns (CouponModel);
	rpc CreateDiscount(CreateDiscountRequest) returns (CouponModel);
	rpc UpdateDiscount(UpdateDiscountRequest) returns (CouponModel);
	rpc DeleteDiscountByProductId(DeleteDiscountByProductIdRequest) returns (DeleteDiscountResponse);
	rpc DeleteDiscountByProductName(DeleteDiscountByProductNameRequest) returns (DeleteDiscountResponse);
}

// Requests
message CreateDiscountRequest {
	CouponModel coupon = 1;
}

message GetDiscountByProductIdRequest {
	string productId = 1; 
}
message GetDiscountByProductNameRequest {
	string productName = 1;
}

message UpdateDiscountRequest {
	CouponModel coupon = 1;
}

message DeleteDiscountByProductIdRequest {
	string productId = 1; 
}

message DeleteDiscountByProductNameRequest {
	string productName = 1;
}

// Responses
message CouponModel {
	int32 id = 1;
	string productName = 2;
	string description = 3;
	int32 amount = 4;
	string productId = 5;
}

message DeleteDiscountResponse {
	bool success = 1;
}